spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#JPA setting
    hibernate:
      ddl_auto: update
    show: true

# managing actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "health, beans, metrics, loggers"
      base-path: "/management-dashboard"
  endpoint:
    health:
      show-details: always
