spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#JPA setting
    hibernate:
      ddl_auto: update
    show: true
